### ISSUE TITLE
Local version doesn't work out of the box without assigning projects

### ISSUE THREAD

**Issue by IMFUZZ** [Kode/KodeGarden#1]
Not sure if really a bug but expected the local version to create an empty project if none assign. Also, not sure where to put projects. :sweat_smile: 

![kodegarden_bug](https://user-images.githubusercontent.com/10481154/30524141-f15572ba-9bbb-11e7-81ad-9a6c8dd83fed.png)

**Comment by RobDangerous** [comment]
Added a readme and a setup script, please test if you can get it running now.

**Comment by RobDangerous** [comment]
Guess this is fixed.
