### ISSUE TITLE
Failed to load resource in console

### ISSUE THREAD

**Issue by nulld** [Kode/KodeGarden#8]
There is error in console. Is `khaworker.js` nessecery? Seems everything is okay with garden despite this error. 
![image](https://user-images.githubusercontent.com/2820168/37554540-8c60b0a4-29eb-11e8-9ecc-e26e40870552.png)

**Comment by RobDangerous** [comment]
khaworker is necessary. But I can't reproduce this, more details please.

**Comment by nulld** [comment]
Can't reproduce it too. Maybe it was temporary network issue.
