### ISSUE TITLE
Code is blinking

### ISSUE THREAD

**Issue by m8mike** [Kode/KodeGarden#9]
Code is constantly blinking in Firefox Quantum 59.0.1 (32-bit).

**Comment by ianharrigan** [comment]
This is fixed in latest KG (not released just yet). If you can believe it it was:

```
.monaco-editor, .monaco-editor .overflow-guard {
    /* border-radius: 3px; stupid html5 / css / js - causes flicker on FF */
}
```

Ian

**Comment by RobDangerous** [comment]
It's finally unblinked.
